export class AiService {
  async generateRoadmap() {
    return 'Roadmap generated by AI';
  }

  async generateCourse() {
    return 'Course generated by AI';
  }

  async generateQuiz() {
    return 'Quiz generated by AI';
  }

  async chat() {
    return 'Chat with AI';
  }

  async roadmapChat() {
    return 'Chat with AI about roadmap';
  }
}
