import { Elysia } from "elysia";

export const aiRouter = new Elysia()
    .group('/ai', (app) =>
        app
            .post('/roadmap', 'Roadmap generated by AI')
            .post('/course', 'Course generated by AI')
            .post('/quiz', 'Quiz generated by AI')
            .post('/chat', 'Chat with AI')
            .post('/roadmap-chat', 'Chat with AI about roadmap')
            
    )
